config/routes.rb
GestaoEscolar::Application.routes.draw do
  get "principal/home"

  resources :professores
  match 'relatorio_professores' => 'professores#relatorio_professores'

  resources :materias

  resources :turmas

  resources :alunos
  match 'relatorio_alunos' => 'alunos#relatorio_alunos'

  root :to => 'principal#home', :as => 'principal'

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :nome, :turma_id
  belongs_to :turma

  validates_presence_of :nome
end

app/models/aula.rb
class Aula < ActiveRecord::Base
  belongs_to :materia
  belongs_to :professor
  belongs_to :turma

  attr_accessible :materia_id, :professor_id

  validates_uniqueness_of :materia_id, :scope => [:turma_id]

  def to_s
  	"#{self.professor} - #{self.materia}"
  end

end

app/models/materia.rb
class Materia < ActiveRecord::Base
  has_many :aulas
  has_many :professores, :through => :aulas
  has_many :turmas, :through => :aulas
  
  attr_accessible :nome, :professor_ids

  validates_presence_of :nome
  validates_uniqueness_of :nome

  def to_s
  	nome
  end
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  has_many :aulas
  has_many :materias, :through => :aulas
  has_many :turmas, :through => :aulas

  attr_accessible :nome, :materia_ids

  validates_presence_of :nome

  def to_s
  	nome
  end
end

app/models/turma.rb
# encoding: UTF-8
class Turma < ActiveRecord::Base
  has_many :alunos
  has_many :aulas, :dependent => :destroy
  has_many :materias, :through => :aulas
  has_many :professores, :through => :aulas

  attr_accessible :nome, :aula_ids, :aulas_attributes, :materias, :professores

  accepts_nested_attributes_for :aulas, :reject_if => :all_blank, :allow_destroy => true

  validates_uniqueness_of :nome
  validates_presence_of :nome
  validates_associated :aulas
  validate :validate_unique_aulas

  def validate_unique_aulas
    validate_uniqueness_of_in_memory(aulas, [:materia_id, :turma_id], 
      'Não é permitido cadastrar matérias duplicadas.')
  end

  def to_s
    nome
  end

end

# Stackoveflow: http://tinyurl.com/4wconxh
module ActiveRecord
  class Base
    # Validate that the the objects in +collection+ are unique
    # when compared against all their non-blank +attrs+. If not
    # add +message+ to the base errors.
    def validate_uniqueness_of_in_memory(collection, attrs, message)
      hashes = collection.inject({}) do |hash, record|
        key = attrs.map {|a| record.send(a).to_s }.join
        if key.blank? || record.marked_for_destruction?
          key = record.object_id
        end
        hash[key] = record unless hash[key]
        hash
      end
      if collection.length > hashes.length
        self.errors.add(:base, :message)
      end
    end
  end
end  

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  respond_to :html
  
  def index
    @alunos = Aluno.find(:all, :order => [:turma_id, :nome])

    respond_with @alunos
  end

  def relatorio_alunos
    @turmas_alunos = Turma.includes(:alunos).joins(:alunos)

    respond_with @turmas_alunos
  end

  def show
    @aluno = Aluno.find(params[:id])

    respond_with @aluno
  end

  def new
    @aluno = Aluno.new

    respond_with @aluno
  end
  
  def edit
    @aluno = Aluno.find(params[:id])
  end
  
  def create
    @aluno = Aluno.new(params[:aluno])

    if @aluno.save
      respond_with @aluno
    else
      render action: "new"
    end    
  end
  
  def update
    @aluno = Aluno.find(params[:id])

    if @aluno.update_attributes(params[:aluno])
      respond_with @aluno
    else
      render action: "edit"
    end    
  end
  
  def destroy
    @aluno = Aluno.find(params[:id])
    @aluno.destroy

    redirect_to alunos_url
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/materias_controller.rb
class MateriasController < ApplicationController
  respond_to :html
  
  def index
    @materias = Materia.all

    respond_with @materias
  end
  
  def show
    @materia = Materia.find(params[:id])

    respond_with @materia
  end

  def new
    @materia = Materia.new

    respond_with @materia
  end

  def edit
    @materia = Materia.find(params[:id])
  end
  
  def create
    @materia = Materia.new(params[:materia])

    if @materia.save
      respond_with @materia
    else
      render action: "new"
    end    
  end

  def update
    @materia = Materia.find(params[:id])

    if @materia.update_attributes(params[:materia])
      respond_with @materia
    else
      render action: "edit"
    end    
  end

  def destroy
    @materia = Materia.find(params[:id])
    @materia.destroy

    redirect_to materias_url
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def home
  end
end

app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
  respond_to :html
  
  def index
    @professores = Professor.all

    respond_with @professores
  end

  def relatorio_professores
    @opcao_filtro = params[:filtro] || "Por turma"
    if @opcao_filtro == "Por turma"
      @turmas_professores = Turma.includes({:professores => [:materias]}, :aulas).joins(:professores, :aulas)
    elsif @opcao_filtro == "Por professor"  
      @professores_turmas = Professor.includes({:turmas => [:materias]}, :aulas).joins(:turmas, :aulas)
    end
  end
  
  def show
    @professor = Professor.find(params[:id])

    respond_with @professor
  end
  
  def new
    @professor = Professor.new

    respond_with @professor
  end

  def edit
    @professor = Professor.find(params[:id])
  end

  def create
    @professor = Professor.new(params[:professor])
    
    if @professor.save
      respond_with @professor
    else
      render action: "new"
    end
  end

  def update
    @professor = Professor.find(params[:id])

    if @professor.update_attributes(params[:professor])
      respond_with @professor
    else
      render action: "edit"
    end    
  end

  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    redirect_to professores_url
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  respond_to :html
  
  def index
    @turmas = Turma.includes(:alunos).all
    
    respond_with @turmas 
  end

  def show
    @turma = Turma.find(params[:id])

    respond_with @turma
  end

  def new
    @turma = Turma.new
    @turma.aulas.build
        
    respond_with @turma
  end

  def edit
    @turma = Turma.find(params[:id])
  end

  def create
    @turma = Turma.new(params[:turma])

    if @turma.save
      respond_with @turma
    else
      render action: "new"
    end
  end

  def update
    @turma = Turma.find(params[:id])

    if @turma.update_attributes(params[:turma])
      respond_with @turma
    else
      render action: "edit"
    end
  end

  def destroy
    @turma = Turma.find(params[:id])
    @turma.destroy

    redirect_to turmas_url
  end
end

app/helpers/alunos_helper.rb
#encoding: UTF-8
module AlunosHelper

  def nenhum_aluno
	"<tr>
	  <td>Não há alunos cadastrados.</td>
	  <td></td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>".html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materias_helper.rb
#encoding: UTF-8
module MateriasHelper
  
  def nenhuma_materia
	"<tr>
	  <td>Não há matérias cadastradas.</td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>".html_safe
  end		
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/professores_helper.rb
#encoding: UTF-8
module ProfessoresHelper

  def nenhum_professor
	"<tr>
	  <td>Não há professores cadastrados.</td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>".html_safe
  end

  def relatorio_vazio
  	"Não há dados de professores relacionados à aulas.<br />".html_safe
  end
end

app/helpers/turmas_helper.rb
#encoding: UTF-8
module TurmasHelper
  def nenhuma_turma
	"<tr>
	  <td>Não há turmas cadastradas.</td>
	  <td></td>
	  <td></td>
	  <td></td>
	</tr>".html_safe
  end			
end

app/views/alunos/_aluno.html.erb
<tr>
    <td><%= aluno.nome %></td>
    <td><%= aluno.turma ? aluno.turma.nome : "O aluno não está registrado em uma turma." %></td>
    <td><%= link_to 'Exibir', aluno %></td>
    <td><%= link_to 'Alterar', edit_aluno_path(aluno) %></td>
    <td><%= link_to 'Excluir', aluno, confirm: 'Tem certeza?', method: :delete %></td>
 </tr>

app/views/alunos/_form.html.erb
<br />
<%= simple_form_for(@aluno, :html => {:class => "form-horizontal"})  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :turma %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/alunos/_rel_aluno.html.erb
<br />
<h2><%= rel_aluno.nome %></h2>
<table class="table table-bordered table-striped">
  <tr>
    <th>Alunos</th>
  </tr>
  <% if rel_aluno.alunos.empty? %>
    <tr>
    <td>Nenhum aluno registrado nesta rel_aluno.</td>
    </tr>
  <% else %>
    <% rel_aluno.alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/alunos/edit.html.erb
<h1>Alterar dados de aluno</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @aluno %> |
<%= link_to 'Voltar', alunos_path %>

app/views/alunos/index.html.erb
<h1>Relação de alunos</h1>
<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th>Turma</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render(@alunos) || nenhum_aluno %>
  
</table>

<br />

<%= link_to 'Cadastrar aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>Novo aluno</h1>

<%= render 'form' %>

<%= link_to 'Voltar', alunos_path %>

app/views/alunos/relatorio_alunos.html.erb
<h1>Relação de alunos por turma</h1>

<%= render(:partial => 'rel_aluno', :collection => @turmas_alunos) || "<br />Não há alunos registrados em turmas.".html_safe %>

app/views/alunos/show.html.erb
<p>
  <b>Nome:</b>
  <%= @aluno.nome %>
</p>


<%= link_to 'Alterar', edit_aluno_path(@aluno) %> |
<%= link_to 'Voltar', alunos_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="jumbotron subhead" id="overview">
<h3>
  <%= link_to "Principal", principal_path %> |
  <%= link_to "Alunos", alunos_path %> |
  <%= link_to "Professores", professores_path %> |
  <%= link_to "Matérias", materias_path %> |
  <%= link_to "Turmas", turmas_path %>
</h3>

<div class="subnav subnav-fixed">
  <ul class="nav nav-pills">
    <li><%= link_to ">> Relatório de alunos", relatorio_alunos_path if controller_name == "alunos" %></li>
    <li><%= link_to ">> Relatório de professores", relatorio_professores_path if controller_name == "professores" %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gestão Escolar" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/materias/_form.html.erb
<br />
<%= simple_form_for(@materia, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/materias/_materia.html.erb
<tr>
  <td><%= materia.nome %></td>
  <td><%= link_to 'Exibir', materia %></td>
  <td><%= link_to 'Alterar', edit_materia_path(materia) %></td>
  <td><%= link_to 'Excluir', materia, confirm: 'Tem certeza?', method: :delete %></td>
</tr>

app/views/materias/edit.html.erb
<h1>Alterar dados de matéria</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @materia %> |
<%= link_to 'Voltar', materias_path %>

app/views/materias/index.html.erb
<h1>Relação de matérias</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render(@materias) || nenhuma_materia %>

</table>

<br />

<%= link_to 'Cadastrar matéria', new_materia_path %>

app/views/materias/new.html.erb
<h1>Adicionar matéria</h1>

<%= render 'form' %>

<%= link_to 'Voltar', materias_path %>

app/views/materias/show.html.erb
<p>
  <b>Nome:</b>
  <%= @materia.nome %>
</p>

<%= link_to 'Alterar', edit_materia_path(@materia) %> |
<%= link_to 'Voltar', materias_path %>

app/views/principal/home.html.erb
<div align="center"><h1>Sistema de Gestão Escolar</h1></div>

app/views/professores/_form.html.erb
<br />
<%= simple_form_for(@professor, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/professores/_prof.html.erb
<br />
<h2><%= prof.nome %></h2>
<table class="table table-bordered table-striped">
  <tr>
    <th>Turma</th>
    <th>Matérias</th>
  </tr>
  <% prof.aulas.each do |aula| %>
    <tr>
      <td><%= aula.turma ? aula.turma.nome : "Não há turma cadastrada" %></td>
      <td><%= aula.materia ? aula.materia.nome : "Não há matéria cadastrada." %></td>
    </tr>
  <% end %>
</table>

app/views/professores/_professor.html.erb
<tr>
  <td><%= professor.nome %></td>
  <td><%= link_to 'Exibir', professor %></td>
  <td><%= link_to 'Alterar', edit_professor_path(professor) %></td>
  <td><%= link_to 'Excluir', professor, confirm: 'Tem certeza?', method: :delete %></td>
</tr>

app/views/professores/_turma.html.erb
<br />
<h2><%= turma.nome %></h2>
<table class="table table-bordered table-striped">
  <tr>
    <th>Professores</th>
    <th>Matérias</th>
  </tr>
  <% turma.aulas.each do |aula| %>
    <tr>
      <td><%= aula.professor.nome %></td>
      <td><%= aula.materia ? aula.materia.nome : "Não há matéria cadastrada." %></td>
    </tr>
  <% end %>
</table>

app/views/professores/edit.html.erb
<h1>Alterar dados de professor</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @professor %> |
<%= link_to 'Voltar', professores_path %>

app/views/professores/index.html.erb
<h1>Relação de professores</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render(@professores) || nenhum_professor %>
</table>

<br />

<%= link_to 'Cadastrar professor', new_professor_path %>

app/views/professores/new.html.erb
<h1>Adicionar professor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', professores_path %>

app/views/professores/relatorio_professores.html.erb
<h1>Relatório de professores</h1>
<br />
<%= form_tag nil, :method => 'get', :id => "form_filter" do %>
  <h3>Filtrar relatório de professores:</h3>
  <%= select_tag :filtro, options_for_select(["Por professor", "Por turma"], @opcao_filtro), :id => "filter" %>
  <%= submit_tag "Filtrar", :style => "display:none;" %>
<% end %>

<% if @opcao_filtro == "Por turma" %>
  <%= render(:partial => "turma", :collection => @turmas_professores) || relatorio_vazio %>
<% end %>

<% if @opcao_filtro == "Por professor" %>
  <%= render(:partial => "prof", :collection => @professores_turmas)  || relatorio_vazio %>
<% end %>

<br />

<%= link_to 'Voltar', professores_path %>

app/views/professores/show.html.erb
<p>
  <b>Nome:</b>
  <%= @professor.nome %>
</p>

<%= link_to 'Alterar', edit_professor_path(@professor) %> |
<%= link_to 'Voltar', professores_path %>

app/views/turmas/_aula_fields.html.erb
<span class="fields">
  <div class="alert alert-info">
    <%= f.association :materia %>
    <%= f.association :professor %>
    <%= f.link_to_remove "Remover esta matéria" %>
  </div>
</span>

app/views/turmas/_form.html.erb
<br />
<%= simple_nested_form_for(@turma, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.simple_fields_for :aulas  %>
    <%= f.link_to_add "Adicionar matéria", :aulas  %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/turmas/_turma.html.erb
<tr>
  <td><%= turma.nome %></td>
  <td><%= link_to 'Exibir', turma %></td>
  <td><%= link_to 'Alterar', edit_turma_path(turma) %></td>
  <td><%= link_to 'Excluir', turma, confirm: 'Tem certeza?', method: :delete %></td>
</tr>

app/views/turmas/edit.html.erb
<h1>Alterar dados de turma</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @turma %> |
<%= link_to 'Voltar', turmas_path %>

app/views/turmas/index.html.erb
<h1>Relação de turmas</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render(@turmas) || nenhuma_turma %>

</table>

<br />

<%= link_to 'Cadastrar turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>Adicionar turma</h1>

<%= render 'form' %>

<%= link_to 'Voltar', turmas_path %>

app/views/turmas/show.html.erb
<p>
  <b>Nome da turma:</b>
  <%= @turma.nome %>
</p>

<%= link_to 'Alterar', edit_turma_path(@turma) %> |
<%= link_to 'Voltar', turmas_path %>